name: Release

env:
  itchio_project: paperpiggy/pixelsweeper
  itchio_channel: html5

on:
  push:
    branches:
      - main

jobs:
  exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: zip -r game.zip . -x "*.git*" ".github*"

      - uses: robpc/itchio-upload-action@v1
        with:
          path: game.zip
          project: ${{ env.itchio_project }}
          channel: ${{ env.itchio_channel }}
          api-key: ${{ secrets.ITCH_API_KEY }}
